name: Run Tests

on:
  workflow_dispatch:
    inputs:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests and collect failures
        run: |
          pytest --junit-xml=results.xml || true
        continue-on-error: true

      - name: Install xmllint
        run: sudo apt-get install -y libxml2-utils

      - name: Display failed test names
        if: failure()
        run: |
          echo "Failed tests:"
          xmllint --xpath '//testcase[failure]/@name' results.xml

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: results.xml
