name: Run Tests

on:
  workflow_dispatch:
    inputs:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-junitxml

      - name: Run tests and collect failures
        run: |
          pytest --junitxml=results.xml || true
        continue-on-error: true

      - name: Display failed test names
        if: failure()
        run: |
          echo "Failed tests:"
          grep '<testcase classname=' results.xml | grep '<failure' | awk -F'"' '{print $4}'

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: results.xml
